import { test, expect } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
const evidence='tests/browser/evidence', authState='tests/browser/.auth/state.json'
async function signIn(page){try{const saved=JSON.parse(await readFile(authState,'utf8'));await page.context().addCookies(saved.cookies);return}catch(e){if(e.code!=='ENOENT')throw e}const r=await page.request.post('/api/auth/sign-in/email',{headers:{origin:'http://localhost:3000'},data:{email:process.env.E2E_ADMIN_EMAIL,password:process.env.E2E_ADMIN_PASSWORD}});expect(r.ok(),await r.text()).toBeTruthy();await mkdir('tests/browser/.auth',{recursive:true});await page.context().storageState({path:authState})}
async function loaded(page,path){await page.goto(path);await expect(page.locator('.o-page')).toBeVisible();await expect(page.locator('.o-loading')).toHaveCount(0);await expect(page.locator('.o-problem')).toHaveCount(0)}
async function capture(page,name){await mkdir(evidence,{recursive:true});await page.screenshot({path:`${evidence}/${name}.png`,animations:'disabled'})}
async function noOverflow(page){const r=await page.evaluate(()=>{const m=document.querySelector('.o-main');return{window:innerWidth,document:document.documentElement.scrollWidth,main:m?.clientWidth||0,content:m?.scrollWidth||0}});expect(r.document).toBeLessThanOrEqual(r.window+1);expect(r.content).toBeLessThanOrEqual(r.main+1)}
test('workspace API and pages keep administrator authorization',async({page})=>{const r=await page.request.get('/api/workspace');expect([401,403]).toContain(r.status());await page.goto('/dashboard');await expect(page).toHaveURL(/\/login/)})
for(const v of[{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}])test(`${v.name}: real pages, responsive bounds, screenshots and event details`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize(v);await signIn(page);for(const path of ['/dashboard','/users','/configs','/calendar','/monitor']){await loaded(page,path);await noOverflow(page);await capture(page,`${v.name}-${path.slice(1)}`)}await page.locator('.o-event').first().click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByText('来源 IP',{exact:true})).toBeVisible();await capture(page,`${v.name}-event-detail`);await page.keyboard.press('Escape');expect(errors).toEqual([])})
test('command search opens real account details',async({page})=>{await signIn(page);await loaded(page,'/dashboard');await page.keyboard.press('Control+k');const s=page.getByRole('combobox',{name:'搜索页面、账户或配置'});await s.fill('lin.design');await expect(page.getByRole('option',{name:/lin.design/})).toBeVisible();await s.press('ArrowDown');await s.press('Enter');await expect(page).toHaveURL(/account=/);await expect(page.getByRole('dialog').getByRole('heading',{name:'lin.design@example.test'})).toBeVisible();await capture(page,'desktop-account-authorization')})
test('new account handoff persists authorization',async({page})=>{await signIn(page);await loaded(page,'/users?new=1');const d=page.getByRole('dialog');await d.getByLabel('账户邮箱',{exact:true}).fill('new.browser@example.test');await d.getByLabel(/日常使用/).check();await d.getByRole('button',{name:'创建账户',exact:true}).click();await expect(d.getByText('账户已创建，授权配置已保存。')).toBeVisible();await expect(d.locator('.o-activation-link')).toContainText('/activate?token=');const data=await(await page.request.get('/api/workspace?view=accounts&q=new.browser')).json();expect(data.users).toHaveLength(1);expect(data.users[0].userConfigs).toHaveLength(1);expect(data.users[0].subscription).not.toHaveProperty('token');await capture(page,'desktop-account-handoff')})
test('quota changes persist without consuming access',async({page})=>{await signIn(page);const a=(await(await page.request.get('/api/workspace?view=accounts&q=quota.test')).json()).users[0];await loaded(page,`/users?account=${a.id}`);const d=page.getByRole('dialog');await d.getByRole('button',{name:'链接与额度',exact:true}).click();await expect(d.getByText('1 次',{exact:true})).toBeVisible();await d.getByLabel('允许的总访问次数').fill('9');await d.getByRole('button',{name:'保存额度',exact:true}).click();const x=(await(await page.request.get(`/api/users/${a.id}/subscription`)).json()).subscription;expect(x.maxAccess).toBe(9);expect(x.accessCount).toBe(1)})
test('invalid YAML is rejected and destructive cancellation does not write',async({page})=>{await signIn(page);const ps=await(await page.request.get('/api/workspace?view=configs')).json(),p=ps.configs.find(x=>x.isActive);await loaded(page,`/configs?config=${p.id}`);const d=page.getByRole('dialog'),original=await d.getByLabel('YAML 配置内容').inputValue();await d.getByLabel('YAML 配置内容').fill('invalid: [');await d.getByRole('button',{name:'检查 YAML 语法'}).click();await expect(d.locator('.o-problem')).toBeVisible();await d.getByLabel('YAML 配置内容').fill(original);await d.getByRole('button',{name:'删除配置',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();expect((await page.request.get(`/api/workspace?view=config&id=${p.id}`)).status()).toBe(200)})
test('failed read is not rendered as healthy empty data',async({page})=>{await signIn(page);await page.route('**/api/workspace',r=>r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'验收：读取失败'})}));await page.goto('/dashboard');await expect(page.locator('.o-problem')).toContainText('验收：读取失败');await expect(page.getByRole('heading',{name:/没有待处理/})).toHaveCount(0);await page.unroute('**/api/workspace');await page.getByRole('button',{name:'重新加载'}).click();await expect(page.locator('.o-hero')).toBeVisible()})
test('dark appearance remains usable and reduced-motion preference is honored by Motion',async({page})=>{await signIn(page);await loaded(page,'/dashboard');await page.getByRole('button',{name:'切换深色主题'}).click();await expect(page.locator('html')).toHaveClass(/dark/);await expect(page.locator('.o-canvas')).toHaveCSS('transform','none');await noOverflow(page);await capture(page,'desktop-dark')})
test('unsaved quota cannot disappear on close or internal link',async({page})=>{await signIn(page);const a=(await(await page.request.get('/api/workspace?view=accounts&q=quota.test')).json()).users[0];await loaded(page,`/users?account=${a.id}`);const d=page.getByRole('dialog');await d.getByRole('button',{name:'链接与额度'}).click();await d.getByLabel('允许的总访问次数').fill('77');await d.getByRole('link',{name:'查看访问记录'}).click();await expect(page).toHaveURL(/\/users\?account=/);await d.getByRole('button',{name:'关闭',exact:true}).click();await expect(page.getByRole('heading',{name:'放弃未保存的修改？'})).toBeVisible();await page.getByRole('button',{name:'取消',exact:true}).click();await expect(d.getByLabel('允许的总访问次数')).toHaveValue('77')})
test('clipboard rejection never reports copied subscription',async({page})=>{await signIn(page);await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('验收：剪贴板权限被拒绝'))},configurable:true}));await loaded(page,'/users');await page.getByRole('button',{name:'复制 lin.design@example.test 的订阅链接'}).click();await expect(page.getByText('验收：剪贴板权限被拒绝')).toBeVisible();await expect(page.getByText('已复制订阅链接，请仅交给授权用户')).toHaveCount(0)})
