'use client'

import Link from 'next/link'
import { ArrowUpRight, Plus } from 'lucide-react'
import { useResource } from '@/hooks/use-workspace'
import { accountHref, accountState, formatDate, type Overview } from '@/lib/workspace'
import { ActivityTimeline, Avatar, DeliveryChart, Empty, Loading, OrbitalArtwork, PageTitle, Problem, Refresh, SectionTitle } from './ui'

export function OverviewPage() {
  const resource = useResource<Overview>('/api/workspace')
  const { data } = resource
  if (!data) return <div className="o-page"><PageTitle eyebrow="YOUR WORKSPACE" title="订阅工作台" description="授权、配置与访问，放在同一个视野里。"/>{resource.error ? <Problem message={resource.error} retry={resource.reload}/> : <Loading/>}</div>
  const { counts } = data
  const start = counts.accounts === 0
  return <div className="o-page">{resource.error && <Problem message={`刷新未完成，以下仍是上次读取的数据。${resource.error}`} retry={resource.reload}/>}<section className="o-hero"><div className="o-hero-copy"><p className="o-eyebrow">SUBSCRIPTION OPERATIONS / 订阅工作台</p><h1>{start ? <>从第一份配置，<br/>开始一次连接。</> : counts.attention ? <>今天，有 <em>{counts.attention}</em> 个账户<br/>需要你看一眼。</> : <>没有待处理的账户。<br/>今天，可以更从容。</>}</h1><p>{start ? '准备配置、分配给用户，再把订阅链接交给他们。' : counts.attention ? '到期、额度不足或缺少配置，都已汇总在下方。' : '已检查启用账户的有效期、访问额度和配置分配条件。'}</p><div className="o-actions"><Link className="o-button" data-variant="primary" href={start ? '/configs?new=1' : counts.attention ? '/users?filter=attention' : '/users'}>{start ? '准备第一份配置' : counts.attention ? '处理待关注账户' : '查看订阅账户'}<ArrowUpRight/></Link><Link className="o-button" href="/users?new=1"><Plus/>创建账户</Link></div></div><OrbitalArtwork/></section><div className="o-overview-facts"><Link href="/users"><strong>{counts.accounts.toLocaleString()}</strong>订阅用户<ArrowUpRight/></Link><Link href="/configs"><strong>{counts.configs.toLocaleString()}</strong>启用配置<ArrowUpRight/></Link><Link href="/monitor?kind=delivery&range=24h"><strong>{counts.deliveries.toLocaleString()}</strong>24h 内容返回<ArrowUpRight/></Link><Link href="/monitor?kind=security&range=24h"><strong>{counts.security.toLocaleString()}</strong>24h 安全提醒<ArrowUpRight/></Link></div><div className="o-dashboard-middle"><section><SectionTitle number="01" title="优先处理"><Link href="/users?filter=attention">全部 {counts.attention} 项<ArrowUpRight/></Link></SectionTitle>{data.attention.length ? data.attention.map(account => { const state = accountState(account, new Date(data.asOf).getTime()); return <div className="o-queue-row" key={account.id}><Avatar name={account.email}/><div className="o-queue-copy"><strong>{account.email}</strong><p>{state.label} · {state.detail}</p></div><Link href={accountHref(account.id)}>{state.action}<ArrowUpRight/></Link></div> }) : <Empty title={start ? '准备好后，从这里开始' : '这份清单是空的'} description={start ? '创建账户后，需要关注的事项会自然出现在这里。' : '当前没有到期、近七天到期、额度用尽或缺少可用配置的启用用户。'}/>}</section><section><SectionTitle number="02" title="订阅返回趋势"><Link href="/monitor?kind=delivery">查看记录<ArrowUpRight/></Link></SectionTitle><DeliveryChart data={data.trend}/></section></div><section className="o-activity-section"><SectionTitle number="03" title="刚刚发生"><Link href="/monitor">打开时间轴<ArrowUpRight/></Link></SectionTitle>{data.activity.length ? <ActivityTimeline items={data.activity} asOf={data.asOf} compact/> : <Empty title="近 24 小时暂无访问动态" description="这里呈现真实的订阅返回与认证事件，不填充演示记录。"/>}</section><div className="o-pager"><span>读取于 {formatDate(data.asOf, true)} · 不代表节点实时连通状态</span><Refresh loading={resource.loading} onClick={resource.reload}/></div></div>
}
