'use client'

import { useId, useState, type ButtonHTMLAttributes, type ReactNode } from 'react'
import Link from 'next/link'
import * as Dialog from '@radix-ui/react-dialog'
import { ArrowDownLeft, ArrowUpRight, Check, ChevronLeft, ChevronRight, CircleAlert, RefreshCw, X } from 'lucide-react'
import { accountHref, formatDate, relativeTime, type Activity, type PageInfo, type Tone } from '@/lib/workspace'

export function Action({ variant = 'secondary', className = '', type = 'button', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'quiet' | 'danger' }) {
  return <button type={type} className={`o-button ${className}`} data-variant={variant} {...props} />
}
export function Pill({ children, tone = 'muted' }: { children: ReactNode; tone?: Tone }) { return <span className="o-pill" data-tone={tone}><i aria-hidden="true" />{children}</span> }
export function Avatar({ name }: { name: string }) { return <span className="o-avatar" aria-hidden="true" data-tone={name.charCodeAt(0) % 4}>{name.slice(0, 2).toUpperCase()}</span> }
export function BrandMark() { return <svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M28 10H17a7 7 0 0 0 0 14h6a3 3 0 0 1 0 6H12" stroke="currentColor" strokeWidth="5" strokeLinecap="round"/><path d="M12 30h11a7 7 0 0 0 0-14h-6a3 3 0 0 1 0-6h11" stroke="currentColor" strokeWidth="5" strokeLinecap="round" opacity=".36"/></svg> }
export function PageTitle({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) {
  return <header className="o-page-title"><div><h1>{title}</h1>{description && <p className="o-description">{description}</p>}</div>{actions && <div className="o-actions">{actions}</div>}</header>
}
export function SectionTitle({ title, children }: { title: string; children?: ReactNode }) { return <div className="o-section-title"><h2>{title}</h2>{children}</div> }
export function Refresh({ loading, onClick }: { loading: boolean; onClick: () => void }) { return <Action variant="quiet" onClick={onClick} disabled={loading} aria-label="刷新数据"><RefreshCw className={loading ? 'o-spin' : ''} />刷新</Action> }
export function Empty({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="o-empty"><span className="o-empty-mark" aria-hidden="true"><BrandMark /></span><h3>{title}</h3>{description && <p>{description}</p>}{action}</div> }
export function Problem({ message, retry }: { message: string; retry?: () => void }) { return <div className="o-problem" role="alert"><CircleAlert/><span>{message}</span>{retry && <Action variant="quiet" onClick={retry}>重新加载</Action>}</div> }
export function Loading() { return <div className="o-loading" role="status" aria-label="正在加载"><div/><div/><div/><span className="sr-only">正在读取数据</span></div> }
export function Pager({ pagination, onPage }: { pagination: PageInfo; onPage: (page: number) => void }) { return <div className="o-pager"><span>共 {pagination.total.toLocaleString()} 项 · 第 {pagination.page} / {Math.max(1, pagination.pageCount)} 页</span><div><Action aria-label="上一页" disabled={pagination.page <= 1} onClick={() => onPage(pagination.page - 1)}><ChevronLeft/></Action><Action aria-label="下一页" disabled={pagination.page >= pagination.pageCount} onClick={() => onPage(pagination.page + 1)}><ChevronRight/></Action></div></div> }
export function Drawer({ title, description, children, onClose, wide = false }: { title: string; description: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  return <Dialog.Root open onOpenChange={open => { if (!open) onClose() }}><Dialog.Portal><Dialog.Overlay className="o-overlay orbit-portal"/><Dialog.Content className="o-drawer orbit-portal" data-wide={wide || undefined}><header className="o-drawer-header"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description></div><Dialog.Close asChild><Action variant="quiet" aria-label="关闭详情"><X/></Action></Dialog.Close></header>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>
}
export function Confirm({ title, description, confirmLabel = '确认操作', onConfirm, onClose, danger = true }: { title: string; description: string; confirmLabel?: string; onConfirm: () => Promise<void>; onClose: () => void; danger?: boolean }) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const submit = async () => { setBusy(true); setError(''); try { await onConfirm(); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : '操作未完成') } finally { setBusy(false) } }
  return <Dialog.Root open onOpenChange={open => { if (!open && !busy) onClose() }}><Dialog.Portal><Dialog.Overlay className="o-overlay orbit-portal"/><Dialog.Content className="o-confirm orbit-portal" onEscapeKeyDown={event => { if (busy) event.preventDefault() }} onInteractOutside={event => event.preventDefault()}><CircleAlert className="o-confirm-icon"/><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description>{error && <Problem message={error}/>}<div className="o-actions"><Action onClick={onClose} disabled={busy}>取消</Action><Action variant={danger ? 'danger' : 'primary'} disabled={busy} onClick={() => void submit()}>{busy ? '正在处理…' : confirmLabel}</Action></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
export function ActivityTimeline({ items, asOf, compact = false }: { items: Activity[]; asOf: string; compact?: boolean }) {
  const [selected, setSelected] = useState<Activity | null>(null)
  return <><div className="o-timeline" data-compact={compact || undefined}>{items.map(item => <button type="button" className="o-event" key={item.id} onClick={() => setSelected(item)} aria-label={`${item.title}，查看详情`}><span className="o-event-track" data-tone={item.tone}>{item.kind === 'delivery' ? <ArrowDownLeft/> : <CircleAlert/>}</span><span className="o-event-copy"><strong>{item.title}</strong><span>{item.detail}</span></span><time dateTime={item.at} title={formatDate(item.at, true)}>{relativeTime(item.at, new Date(asOf).getTime())}</time><ArrowUpRight className="o-event-arrow"/></button>)}</div>{selected && <Drawer title={selected.title} description={selected.detail} onClose={() => setSelected(null)}><div className="o-drawer-body"><Pill tone={selected.tone}>{selected.kind === 'delivery' ? '订阅返回记录' : '认证与安全记录'}</Pill><div className="o-insight"><h3>{selected.kind === 'delivery' ? '结果说明' : '处理建议'}</h3><p>{selected.nextStep}</p></div><dl className="o-facts"><div><dt>发生时间</dt><dd>{formatDate(selected.at, true)}</dd></div><div><dt>来源 IP</dt><dd><code>{selected.ip}</code></dd></div><div><dt>响应状态</dt><dd>{selected.status ?? '未记录'}</dd></div><div><dt>客户端</dt><dd className="o-break">{selected.agent || '未提供客户端信息'}</dd></div></dl></div><footer className="o-drawer-footer">{selected.userId ? <Link prefetch={false} className="o-button" data-variant="primary" href={accountHref(selected.userId)}>查看关联账户<ArrowUpRight/></Link> : <p className="o-muted">这条请求未关联到可识别的账户。</p>}</footer></Drawer>}</>
}
export function DeliveryChart({ data }: { data: { date: string; count: number }[] }) {
  const id = useId().replace(/:/g, '')
  const [hovered, setHovered] = useState<number | null>(null)
  const maximum = Math.max(1, ...data.map(item => item.count))
  const points = data.map((item, index) => `${30 + index * 60},${150 - (item.count / maximum) * 120}`).join(' ')
  const total = data.reduce((sum, item) => sum + item.count, 0)
  return <div className="o-chart"><div className="o-chart-value"><strong>{(hovered === null ? total : data[hovered].count).toLocaleString()}</strong><span>{hovered === null ? '近 7 天 · UTC' : `${data[hovered].date} · 返回次数`}</span></div><svg viewBox="0 0 420 180" role="img" aria-label={`近七日订阅内容返回，共 ${total} 次；下方日期可打开当日记录。`}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop stopColor="currentColor" stopOpacity=".17"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs>{[30, 90, 150].map(y => <path key={y} d={`M30 ${y}H390`} stroke="currentColor" strokeOpacity=".1" strokeDasharray="3 5"/>)}<polygon points={`30,150 ${points} 390,150`} fill={`url(#${id})`}/><polyline points={points} stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" fill="none"/>{data.map((item, index) => <circle key={item.date} cx={30 + index * 60} cy={150 - (item.count / maximum) * 120} r={hovered === index ? 6 : 3} fill="currentColor"/>)}</svg><div className="o-chart-days">{data.map((item, index) => <Link prefetch={false} key={item.date} href={`/monitor?kind=delivery&from=${item.date}T00:00:00.000Z&to=${item.date}T23:59:59.999Z`} onMouseEnter={() => setHovered(index)} onMouseLeave={() => setHovered(null)} onFocus={() => setHovered(index)} onBlur={() => setHovered(null)} aria-label={`${item.date} 返回 ${item.count} 次，查看当天记录`}>{item.date.slice(5).replace('-', '/')}</Link>)}</div><p className="o-footnote">UTC 分日 · 今日未结束</p></div>
}
export function Saved({ children }: { children: ReactNode }) { return <div className="o-saved" role="status"><Check/>{children}</div> }
