'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  AlertTriangle,
  Braces,
  CheckCircle2,
  Code2,
  FileCode2,
  FileText,
  Pencil,
  Plus,
  Power,
  RefreshCw,
  Trash2,
} from 'lucide-react'
import { authClient } from '@/lib/auth-client'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge, EmptyState, PageHeader, Section, StatCard } from '@/components/ui/saas'

interface Config {
  id: string
  name: string
  content: string
  isActive: boolean
  createdAt: string
  user: {
    email: string
  }
}

type PaginatedResponse<T> = {
  [key: string]: T[] | { page: number; pageSize: number; total: number; pageCount: number } | undefined
  pagination?: { page: number; pageSize: number; total: number; pageCount: number }
}

async function fetchAllPages<T>(
  basePath: string,
  collectionKey: string,
  params: Record<string, string> = {}
): Promise<T[]> {
  const pageSize = 100
  let page = 1
  let pageCount = 1
  const items: T[] = []

  do {
    const searchParams = new URLSearchParams({ ...params, page: String(page), pageSize: String(pageSize) })
    const response = await fetch(`${basePath}?${searchParams.toString()}`)
    if (!response.ok) throw new Error(`Failed to fetch ${collectionKey}`)

    const data = await response.json() as PaginatedResponse<T>
    items.push(...((data[collectionKey] as T[] | undefined) || []))
    pageCount = data.pagination?.pageCount || 1
    page += 1
  } while (page <= pageCount)

  return items
}

function getContentStats(content: string) {
  return {
    lines: content.split('\n').length,
    bytes: new Blob([content]).size,
  }
}

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function formatDate(dateString: string) {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

const starterTemplate = `# Clash Configuration Template
# Generated by Subscription Manager

port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info

proxies:
  # Add your proxies here

proxy-groups:
  # Add your proxy groups here

rules:
  - MATCH,DIRECT
`

export default function ConfigsPage() {
  const { data: session } = authClient.useSession()
  const [configs, setConfigs] = useState<Config[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingConfig, setEditingConfig] = useState<Config | null>(null)
  const [formData, setFormData] = useState({ name: '', content: '' })
  const [error, setError] = useState('')

  const fetchConfigs = useCallback(async () => {
    setRefreshing(true)
    try {
      const allConfigs = await fetchAllPages<Config>('/api/configs', 'configs', { includeContent: 'true' })
      setConfigs(allConfigs)
    } catch {
      setError('Failed to fetch configurations')
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }, [])

  useEffect(() => {
    void fetchConfigs()
  }, [fetchConfigs])

  const summary = useMemo(() => {
    return configs.reduce(
      (result, config) => {
        const stats = getContentStats(config.content)
        result.lines += stats.lines
        result.bytes += stats.bytes
        if (config.isActive) result.active += 1
        return result
      },
      { active: 0, lines: 0, bytes: 0 }
    )
  }, [configs])

  const handleCreate = async (event: React.FormEvent) => {
    event.preventDefault()
    setError('')

    try {
      const response = await fetch('/api/configs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...formData, userId: session?.user?.id }),
      })
      const data = await response.json()
      if (!response.ok) {
        setError(data.error)
        return
      }

      setDialogOpen(false)
      setFormData({ name: '', content: '' })
      void fetchConfigs()
    } catch {
      setError('Failed to create configuration')
    }
  }

  const handleUpdate = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!editingConfig) return
    setError('')

    try {
      const response = await fetch(`/api/configs/${editingConfig.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      })
      const data = await response.json()
      if (!response.ok) {
        setError(data.error)
        return
      }

      setDialogOpen(false)
      setEditingConfig(null)
      setFormData({ name: '', content: '' })
      void fetchConfigs()
    } catch {
      setError('Failed to update configuration')
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this configuration?')) return

    try {
      await fetch(`/api/configs/${id}`, { method: 'DELETE' })
      void fetchConfigs()
    } catch {
      setError('Failed to delete configuration')
    }
  }

  const handleToggleActive = async (config: Config) => {
    try {
      await fetch(`/api/configs/${config.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isActive: !config.isActive }),
      })
      void fetchConfigs()
    } catch {
      setError('Failed to update configuration status')
    }
  }

  const openCreateDialog = () => {
    setEditingConfig(null)
    setFormData({ name: '', content: starterTemplate })
    setError('')
    setDialogOpen(true)
  }

  const openEditDialog = (config: Config) => {
    setEditingConfig(config)
    setFormData({ name: config.name, content: config.content })
    setError('')
    setDialogOpen(true)
  }

  if (loading) {
    return (
      <div className="flex h-64 flex-col items-center justify-center gap-3">
        <div className="flex h-9 w-9 items-center justify-center rounded-lg border border-border bg-background-secondary text-accent-primary">
          <Braces className="h-4 w-4 animate-pulse" />
        </div>
        <div className="text-sm text-foreground-muted">Loading configuration library…</div>
      </div>
    )
  }

  return (
    <div className="saas-page">
      <PageHeader
        eyebrow="Delivery infrastructure"
        icon={Braces}
        title="Configurations"
        description="Manage the YAML assets delivered to subscription accounts."
        actions={
          <>
            <Button variant="secondary" size="sm" onClick={() => void fetchConfigs()} disabled={refreshing}>
              <RefreshCw className={refreshing ? 'animate-spin' : ''} />
              Refresh
            </Button>
            <Button size="sm" onClick={openCreateDialog}>
              <Plus />
              New configuration
            </Button>
          </>
        }
      />

      {error && !dialogOpen && (
        <div className="flex items-center gap-2 rounded-xl border border-accent-error/30 bg-accent-error/10 p-4 text-sm text-accent-error">
          <AlertTriangle className="h-4 w-4" />
          <span>{error}</span>
        </div>
      )}

      <section className="metric-strip" aria-label="Configuration summary">
        <StatCard label="Configuration assets" value={configs.length.toLocaleString()} description="Total YAML documents" icon={FileText} />
        <StatCard label="Active" value={summary.active.toLocaleString()} description="Available for delivery" icon={CheckCircle2} tone="success" />
        <StatCard label="Source lines" value={summary.lines.toLocaleString()} description="Across existing assets" icon={Code2} tone="info" />
        <StatCard label="Storage" value={formatBytes(summary.bytes)} description="Current YAML payload size" icon={FileCode2} tone="primary" />
      </section>

      <Section
        title="Configuration library"
        description="Review status, ownership, size, and source content without switching between cards."
        contentClassName="p-0"
      >
        {configs.length === 0 ? (
          <EmptyState
            icon={FileCode2}
            title="No configurations yet"
            description="Create a YAML configuration to make it available for subscription assignment."
            action={<Button size="sm" onClick={openCreateDialog}><Plus />New configuration</Button>}
          />
        ) : (
          configs.map((config) => {
            const stats = getContentStats(config.content)
            return (
              <article key={config.id} className="border-b border-border-subtle last:border-b-0">
                <div className="flex flex-col gap-4 px-4 py-4 sm:px-5 lg:flex-row lg:items-center">
                  <div className="flex min-w-0 flex-1 items-center gap-3">
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-border bg-background-tertiary text-accent-primary">
                      <FileCode2 className="h-4 w-4" />
                    </div>
                    <div className="min-w-0">
                      <div className="truncate text-[13px] font-medium text-foreground-primary">{config.name}</div>
                      <div className="mt-1 flex flex-wrap items-center gap-1.5">
                        <Badge variant={config.isActive ? 'success' : 'neutral'}>{config.isActive ? 'Active' : 'Disabled'}</Badge>
                        <Badge variant="neutral">YAML</Badge>
                        <span className="truncate text-[10px] text-foreground-muted">{config.user.email}</span>
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-4 text-[11px] lg:w-[22rem]">
                    <div>
                      <div className="section-label">Lines</div>
                      <div className="mt-1 tabular-nums font-medium text-foreground-secondary">{stats.lines.toLocaleString()}</div>
                    </div>
                    <div>
                      <div className="section-label">Size</div>
                      <div className="mt-1 tabular-nums font-medium text-foreground-secondary">{formatBytes(stats.bytes)}</div>
                    </div>
                    <div>
                      <div className="section-label">Created</div>
                      <div className="mt-1 truncate tabular-nums font-medium text-foreground-secondary">{formatDate(config.createdAt)}</div>
                    </div>
                  </div>

                  <div className="flex shrink-0 items-center gap-1">
                    <Button variant="ghost" size="icon-sm" onClick={() => void handleToggleActive(config)} title={config.isActive ? 'Disable configuration' : 'Enable configuration'}>
                      <Power className={config.isActive ? 'text-accent-success' : undefined} />
                    </Button>
                    <Button variant="ghost" size="icon-sm" onClick={() => openEditDialog(config)} title="Edit configuration">
                      <Pencil />
                    </Button>
                    <Button variant="ghost" size="icon-sm" onClick={() => void handleDelete(config.id)} title="Delete configuration" className="hover:text-accent-error">
                      <Trash2 />
                    </Button>
                  </div>
                </div>

                <div className="border-t border-border-subtle bg-background-tertiary px-4 py-3 sm:px-5">
                  <pre className="max-h-24 overflow-hidden whitespace-pre-wrap break-all font-mono text-[10px] leading-5 text-foreground-muted">
                    {config.content.slice(0, 420)}
                  </pre>
                </div>
              </article>
            )
          })
        )}
      </Section>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-3xl p-0">
          <DialogHeader>
            <DialogTitle>{editingConfig ? 'Edit configuration' : 'Create configuration'}</DialogTitle>
          </DialogHeader>
          <form onSubmit={editingConfig ? handleUpdate : handleCreate} className="space-y-5 p-5">
            {error && (
              <div className="flex items-center gap-2 rounded-lg border border-accent-error/30 bg-accent-error/10 p-3 text-sm text-accent-error">
                <AlertTriangle className="h-4 w-4" />
                <span>{error}</span>
              </div>
            )}

            <div className="space-y-2">
              <Label htmlFor="name" className="text-xs text-foreground-secondary">Configuration name</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(event) => setFormData({ ...formData, name: event.target.value })}
                placeholder="Production subscription"
                required
              />
            </div>

            <div className="space-y-2">
              <div className="flex items-center justify-between gap-3">
                <Label htmlFor="content" className="text-xs text-foreground-secondary">YAML content</Label>
                <Badge variant="neutral">{getContentStats(formData.content).lines} lines · {formatBytes(getContentStats(formData.content).bytes)}</Badge>
              </div>
              <textarea
                id="content"
                value={formData.content}
                onChange={(event) => setFormData({ ...formData, content: event.target.value })}
                className="min-h-[24rem] w-full resize-y rounded-lg border border-border bg-background-primary p-4 font-mono text-xs leading-6 text-foreground-secondary placeholder:text-foreground-placeholder focus:border-border-strong focus:outline-none focus:ring-2 focus:ring-ring"
                required
                spellCheck={false}
              />
            </div>

            <div className="flex justify-end gap-2 border-t border-border-subtle pt-4">
              <Button type="button" variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
              <Button type="submit">{editingConfig ? 'Save changes' : 'Create configuration'}</Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  )
}
