'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  AlertTriangle,
  Braces,
  CheckCircle2,
  Code2,
  FileCode2,
  FileText,
  Pencil,
  Plus,
  Power,
  RefreshCw,
  Trash2,
} from 'lucide-react'
import { authClient } from '@/lib/auth-client'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge, EmptyState, PageHeader, StatCard } from '@/components/ui/saas'

interface Config {
  id: string
  name: string
  content: string
  isActive: boolean
  createdAt: string
  user: {
    email: string
  }
}

type PaginatedResponse<T> = {
  [key: string]: T[] | { page: number; pageSize: number; total: number; pageCount: number } | undefined
  pagination?: { page: number; pageSize: number; total: number; pageCount: number }
}

async function fetchAllPages<T>(
  basePath: string,
  collectionKey: string,
  params: Record<string, string> = {}
): Promise<T[]> {
  const pageSize = 100
  let page = 1
  let pageCount = 1
  const items: T[] = []

  do {
    const searchParams = new URLSearchParams({ ...params, page: String(page), pageSize: String(pageSize) })
    const response = await fetch(`${basePath}?${searchParams.toString()}`)
    if (!response.ok) throw new Error(`Failed to fetch ${collectionKey}`)

    const data = await response.json() as PaginatedResponse<T>
    items.push(...((data[collectionKey] as T[] | undefined) || []))
    pageCount = data.pagination?.pageCount || 1
    page += 1
  } while (page <= pageCount)

  return items
}

function getContentStats(content: string) {
  return {
    lines: content.split('\n').length,
    bytes: new Blob([content]).size,
  }
}

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function formatDate(dateString: string) {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

const starterTemplate = `# Clash Configuration Template
# Generated by Subscription Manager

port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info

proxies:
  # Add your proxies here

proxy-groups:
  # Add your proxy groups here

rules:
  - MATCH,DIRECT
`

export default function ConfigsPage() {
  const { data: session } = authClient.useSession()
  const [configs, setConfigs] = useState<Config[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingConfig, setEditingConfig] = useState<Config | null>(null)
  const [formData, setFormData] = useState({ name: '', content: '' })
  const [error, setError] = useState('')

  const fetchConfigs = useCallback(async () => {
    setRefreshing(true)
    try {
      const allConfigs = await fetchAllPages<Config>('/api/configs', 'configs', { includeContent: 'true' })
      setConfigs(allConfigs)
    } catch {
      setError('Failed to fetch configurations')
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }, [])

  useEffect(() => {
    void fetchConfigs()
  }, [fetchConfigs])

  const summary = useMemo(() => {
    return configs.reduce(
      (result, config) => {
        const stats = getContentStats(config.content)
        result.lines += stats.lines
        result.bytes += stats.bytes
        if (config.isActive) result.active += 1
        return result
      },
      { active: 0, lines: 0, bytes: 0 }
    )
  }, [configs])

  const handleCreate = async (event: React.FormEvent) => {
    event.preventDefault()
    setError('')

    try {
      const response = await fetch('/api/configs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...formData, userId: session?.user?.id }),
      })
      const data = await response.json()
      if (!response.ok) {
        setError(data.error)
        return
      }

      setDialogOpen(false)
      setFormData({ name: '', content: '' })
      void fetchConfigs()
    } catch {
      setError('Failed to create configuration')
    }
  }

  const handleUpdate = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!editingConfig) return
    setError('')

    try {
      const response = await fetch(`/api/configs/${editingConfig.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      })
      const data = await response.json()
      if (!response.ok) {
        setError(data.error)
        return
      }

      setDialogOpen(false)
      setEditingConfig(null)
      setFormData({ name: '', content: '' })
      void fetchConfigs()
    } catch {
      setError('Failed to update configuration')
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this configuration?')) return

    try {
      await fetch(`/api/configs/${id}`, { method: 'DELETE' })
      void fetchConfigs()
    } catch {
      setError('Failed to delete configuration')
    }
  }

  const handleToggleActive = async (config: Config) => {
    try {
      await fetch(`/api/configs/${config.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isActive: !config.isActive }),
      })
      void fetchConfigs()
    } catch {
      setError('Failed to update configuration status')
    }
  }

  const openCreateDialog = () => {
    setEditingConfig(null)
    setFormData({ name: '', content: starterTemplate })
    setError('')
    setDialogOpen(true)
  }

  const openEditDialog = (config: Config) => {
    setEditingConfig(config)
    setFormData({ name: config.name, content: config.content })
    setError('')
    setDialogOpen(true)
  }

  if (loading) {
    return (
      <div className="flex h-64 flex-col items-center justify-center gap-3">
        <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-accent-primary/10 text-accent-primary">
          <Braces className="h-5 w-5 animate-pulse" />
        </div>
        <div className="text-sm text-foreground-muted">Loading configuration library…</div>
      </div>
    )
  }

  return (
    <div className="saas-page">
      <PageHeader
        eyebrow="Delivery infrastructure"
        icon={Braces}
        title="Configurations"
        description="Maintain the existing YAML assets assigned to subscription accounts."
        actions={
          <>
            <Button variant="secondary" size="sm" onClick={() => void fetchConfigs()} disabled={refreshing}>
              <RefreshCw className={refreshing ? 'animate-spin' : ''} />
              Refresh
            </Button>
            <Button size="sm" onClick={openCreateDialog}>
              <Plus />
              New configuration
            </Button>
          </>
        }
      />

      {error && !dialogOpen && (
        <div className="flex items-center gap-2 rounded-2xl border border-accent-error/30 bg-accent-error/10 p-4 text-sm text-accent-error">
          <AlertTriangle className="h-4 w-4" />
          <span>{error}</span>
        </div>
      )}

      <section className="grid grid-cols-2 gap-3 xl:grid-cols-4">
        <StatCard label="Configuration assets" value={configs.length.toLocaleString()} description="Total YAML documents" icon={FileText} />
        <StatCard label="Active" value={summary.active.toLocaleString()} description="Available for delivery" icon={CheckCircle2} tone="success" />
        <StatCard label="Source lines" value={summary.lines.toLocaleString()} description="Across existing assets" icon={Code2} tone="info" />
        <StatCard label="Storage" value={formatBytes(summary.bytes)} description="Current YAML payload size" icon={FileCode2} tone="primary" />
      </section>

      {configs.length === 0 ? (
        <EmptyState
          icon={FileCode2}
          title="No configurations yet"
          description="Create a YAML configuration to make it available for subscription assignment."
          action={<Button size="sm" onClick={openCreateDialog}><Plus />New configuration</Button>}
        />
      ) : (
        <section className="grid gap-3 md:grid-cols-2 2xl:grid-cols-3">
          {configs.map((config) => {
            const stats = getContentStats(config.content)
            return (
              <Card key={config.id} className="group overflow-hidden hover:-translate-y-0.5 hover:border-border-hover">
                <CardContent className="p-4 sm:p-5">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex min-w-0 items-center gap-3">
                      <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent-primary/10 text-accent-primary ring-1 ring-inset ring-accent-primary/15">
                        <FileCode2 className="h-5 w-5" />
                      </div>
                      <div className="min-w-0">
                        <div className="truncate text-sm font-semibold text-foreground-primary">{config.name}</div>
                        <div className="mt-1 flex items-center gap-1.5">
                          <Badge variant={config.isActive ? 'success' : 'neutral'}>{config.isActive ? 'Active' : 'Disabled'}</Badge>
                          <Badge variant="neutral">YAML</Badge>
                        </div>
                      </div>
                    </div>
                    <div className="flex shrink-0 items-center gap-0.5">
                      <Button variant="ghost" size="icon-sm" onClick={() => void handleToggleActive(config)} title={config.isActive ? 'Disable configuration' : 'Enable configuration'}>
                        <Power className={config.isActive ? 'text-accent-success' : undefined} />
                      </Button>
                      <Button variant="ghost" size="icon-sm" onClick={() => openEditDialog(config)} title="Edit configuration">
                        <Pencil />
                      </Button>
                      <Button variant="ghost" size="icon-sm" onClick={() => void handleDelete(config.id)} title="Delete configuration" className="hover:text-accent-error">
                        <Trash2 />
                      </Button>
                    </div>
                  </div>

                  <div className="mt-5 grid grid-cols-3 gap-2">
                    <div className="rounded-xl bg-background-secondary/70 p-3 ring-1 ring-inset ring-border/70">
                      <div className="text-[10px] uppercase tracking-wider text-foreground-muted">Lines</div>
                      <div className="mt-1 text-sm font-semibold">{stats.lines.toLocaleString()}</div>
                    </div>
                    <div className="rounded-xl bg-background-secondary/70 p-3 ring-1 ring-inset ring-border/70">
                      <div className="text-[10px] uppercase tracking-wider text-foreground-muted">Size</div>
                      <div className="mt-1 text-sm font-semibold">{formatBytes(stats.bytes)}</div>
                    </div>
                    <div className="rounded-xl bg-background-secondary/70 p-3 ring-1 ring-inset ring-border/70">
                      <div className="text-[10px] uppercase tracking-wider text-foreground-muted">Created</div>
                      <div className="mt-1 truncate text-sm font-semibold">{formatDate(config.createdAt)}</div>
                    </div>
                  </div>

                  <div className="mt-4 overflow-hidden rounded-xl bg-[#0d0d10] ring-1 ring-inset ring-border/70">
                    <div className="flex items-center justify-between border-b border-border/70 px-3 py-2 text-[10px] text-foreground-muted">
                      <span>Preview</span>
                      <span>{config.user.email}</span>
                    </div>
                    <pre className="max-h-28 overflow-hidden whitespace-pre-wrap break-all p-3 font-mono text-[10px] leading-5 text-foreground-muted">
                      {config.content.slice(0, 360)}
                    </pre>
                  </div>
                </CardContent>
              </Card>
            )
          })}
        </section>
      )}

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-3xl p-0">
          <DialogHeader>
            <DialogTitle>{editingConfig ? 'Edit configuration' : 'Create configuration'}</DialogTitle>
          </DialogHeader>
          <form onSubmit={editingConfig ? handleUpdate : handleCreate} className="space-y-5 p-5">
            {error && (
              <div className="flex items-center gap-2 rounded-xl border border-accent-error/30 bg-accent-error/10 p-3 text-sm text-accent-error">
                <AlertTriangle className="h-4 w-4" />
                <span>{error}</span>
              </div>
            )}

            <div className="space-y-2">
              <Label htmlFor="name" className="text-xs text-foreground-secondary">Configuration name</Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(event) => setFormData({ ...formData, name: event.target.value })}
                placeholder="Production subscription"
                required
              />
            </div>

            <div className="space-y-2">
              <div className="flex items-center justify-between gap-3">
                <Label htmlFor="content" className="text-xs text-foreground-secondary">YAML content</Label>
                <Badge variant="neutral">{getContentStats(formData.content).lines} lines · {formatBytes(getContentStats(formData.content).bytes)}</Badge>
              </div>
              <textarea
                id="content"
                value={formData.content}
                onChange={(event) => setFormData({ ...formData, content: event.target.value })}
                className="min-h-[24rem] w-full resize-y rounded-xl border border-border bg-[#0d0d10] p-4 font-mono text-xs leading-6 text-foreground-secondary shadow-inner placeholder:text-foreground-placeholder focus:border-border-strong focus:outline-none focus:ring-4 focus:ring-ring"
                required
                spellCheck={false}
              />
            </div>

            <div className="flex justify-end gap-2 border-t border-border pt-4">
              <Button type="button" variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
              <Button type="submit">{editingConfig ? 'Save changes' : 'Create configuration'}</Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  )
}
